### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by peerbolte** [Mixd/wp-deploy#148]
In the installation docs you have the following command:

``git clone git@github.com:Mixd/wp-deploy.git .``

But this gives a permission denied, I think it should be:

``git clone https://github.com/Mixd/wp-deploy.git .``

**Comment by DrizzlyOwl** [comment]
Hi @peerbolte, the first URL `git@github.com:Mixd/wp-deploy.git` requires you to have an SSH key set up on your GitHub account. If you haven't set this up you will receive  the `permission denied (publickey)` response.

**Comment by peerbolte** [comment]
That fixes it. Is there a advantage of using ``git@`` over ``https``, otherwise ``https`` might be more user-friendly?

**Comment by Kukunin** [comment]
When you do `git@` you authenticate with your SSH key automatically. When you do `https`, you don't authenticate. In case you want to just read a public repository, `https` is easier. Otherwise, if you want to push to a repo, or get access to private repo, you need authentication, so `git@` is better.

**Comment by lukewhitehouse** [comment]
Pretty much what @Kukunin said
