### ISSUE TITLE
mysql dump on the ha branch needs password escaping

### ISSUE THREAD

**Issue by JimChestnutt** [Mixd/wp-deploy#165]
https://github.com/Mixd/wp-deploy/blob/55d5d429deba0179cd3ff7ff56526cf844e1e385/lib/capistrano/tasks/db.rake#L100

from `-p#{database['password']}`

to `-p'#{database['password']}'`

**Comment by DrizzlyOwl** [comment]
I think you need to escape the ‘ with a backslash otherwise they might get
caught up in the password text if another ‘ appears in the string.

On 6 December 2018 at 15:15:38, Jim Chestnutt (notifications@github.com)
wrote:

https://github.com/Mixd/wp-deploy/blob/55d5d429deba0179cd3ff7ff56526cf844e1e385/lib/capistrano/tasks/db.rake#L100

from -p#{database['password']}

to -p'#{database['password']}'

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Mixd/wp-deploy/issues/165>, or mute the thread
