### ISSUE TITLE
Themes and plugins are not saved in the 'content' directory

### ISSUE THREAD

**Issue by ltarasiewicz** [Mixd/wp-deploy#48]
I've been trying to set up Wp-deploy for some time and failed. While the deployment and db migration tasks seem to be working properly, I am not able to access the Wordpress site on my staging server. The site is looking for its themes in the  'content' folder as expected. Why then themes and plugins are isntalled in wordpress/wp-conent instead of the desired 'content' directory?

Also, when setting Wp-deploy up, am I supposed to install wordpress manually on the staging server. Ir do I install manually locally, and push the code base and db to the remote server without first installing wordpress therough the famous 5-min install?

Thank you!

**Comment by lukewhitehouse** [comment]
Hi @ltarasiewicz,

First of all thanks for trying wp-deploy out, hopefully we can work together a little and solve your problems.

1. The reason for everything being setup at `/wordpress` is because wp-deploy uses WordPress as a submodule. When you first setup your site with wp-deploy, you'll need to login via `domain.com/wordpress/wp-admin` then go to Settings>Permalink. From then on, you can access wordpress via `domain.com/wp-admin` although technically, everything is still in `/wordpress/`.

2. You don't need to manually setup your WordPress sites when you're on the staging/production servers. When you're ready to push things to an environment, go through the following steps (assuming your repository or Github is up to date):
    1. `bundle exec cap staging wp:setup:remote`
    2. `bundle exec cap staging deploy`
    3. `bundle exec cap staging db:push`
    4. `bundle exec cap staging uploads:push`

That should set everything up for you.
