### ISSUE TITLE
wp:core:update is very inconsistent

### ISSUE THREAD

**Issue by lukewhitehouse** [Mixd/wp-deploy#75]
Sometimes it works and checks out the latest version of WordPress, other times it will checkout a really old version.

**Comment by lustremedia** [comment]
I just tried to update core to 4.2 and it pulled 3.7.7?

**Comment by clov3rly** [comment]
Yes, I found the same thing. Seems to update to the most recent tagged version, and it appears WP released updates for 4.2, 4.1.3, 4.0.3, 3.9.5, 3.8.7, and 3.7.7, in that order, at almost the same time. So the update command chose the most recent, 3.7.7. Probably just needs to parse the entire list of tags, rather than choosing the most recent. If I get some time today, I'll write up a patch for PR.

**Comment by ryanjkoehler** [comment]
+1

**Comment by clov3rly** [comment]
That pull-request should fix it, let me know if you find any issues with it.

**Comment by clov3rly** [comment]
An alternative that I've also used, is to `cd` into the local wordpress submodule, run `git fetch --tags`, and search for the latest tagged release with [`git lola`](http://blog.kfish.org/2010/04/git-lola.html). 

Then, I usually `git checkout` the commit *immediately prior* to the tagged commit, (as the tagged releases are [annotated tags](http://git-scm.com/book/en/v2/Git-Basics-Tagging#Creating-Tags), which have their own commit SHA, and are not pulled down by `git fetch` without `--tags` appended.

`cd` back into your project directory, and commit the changes the submodule, then you can `cap production push` as normal.

Or you can checkout the tag itself, but you'll need to run `cap production cache:repo:purge` so that the remote submodule is purged and will pull in the full list of tags next time you push.

**Comment by cornelous** [comment]
Any fix to this one yet?

**Comment by lustremedia** [comment]
@clov3rly fix has been submitted, and it works.

**Comment by lukewhitehouse** [comment]
@cornelous As @lustremedia said, take a look into the PR. I'm going to be pushing up a bug-fixing release later tonight to solve some of these lingering issues.

In the long term, we're working on building wp-deploy from the ground up so watch this space!
